db:
  properties:
        file: C:\Onkar\Cafe Shop Project\cafeshop\DBProperties.txt

  
server:
  port: 1002
  
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
