db:
  properties:
        file: D:\Nusta Eclipse\DB\DBProperties.txt

  
server:
  port: 9100
  
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
